// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: base_service/proto/base.proto

package hskbasepb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_base_service_proto_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_service_proto_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_base_service_proto_base_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_base_service_proto_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_service_proto_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_base_service_proto_base_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_base_service_proto_base_proto protoreflect.FileDescriptor

const file_base_service_proto_base_proto_rawDesc = "" +
	"\n" +
	"\x1dbase_service/proto/base.proto\x12\thskbasepb\x1a(third_party/google/api/annotations.proto\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2Y\n" +
	"\aHskBase\x12N\n" +
	"\x06Health\x12\x18.hskbasepb.HealthRequest\x1a\x19.hskbasepb.HealthResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/healthB\x11Z\x0f/base;hskbasepbb\x06proto3"

var (
	file_base_service_proto_base_proto_rawDescOnce sync.Once
	file_base_service_proto_base_proto_rawDescData []byte
)

func file_base_service_proto_base_proto_rawDescGZIP() []byte {
	file_base_service_proto_base_proto_rawDescOnce.Do(func() {
		file_base_service_proto_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_service_proto_base_proto_rawDesc), len(file_base_service_proto_base_proto_rawDesc)))
	})
	return file_base_service_proto_base_proto_rawDescData
}

var file_base_service_proto_base_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_base_service_proto_base_proto_goTypes = []any{
	(*HealthRequest)(nil),  // 0: hskbasepb.HealthRequest
	(*HealthResponse)(nil), // 1: hskbasepb.HealthResponse
}
var file_base_service_proto_base_proto_depIdxs = []int32{
	0, // 0: hskbasepb.HskBase.Health:input_type -> hskbasepb.HealthRequest
	1, // 1: hskbasepb.HskBase.Health:output_type -> hskbasepb.HealthResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_base_service_proto_base_proto_init() }
func file_base_service_proto_base_proto_init() {
	if File_base_service_proto_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_service_proto_base_proto_rawDesc), len(file_base_service_proto_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_base_service_proto_base_proto_goTypes,
		DependencyIndexes: file_base_service_proto_base_proto_depIdxs,
		MessageInfos:      file_base_service_proto_base_proto_msgTypes,
	}.Build()
	File_base_service_proto_base_proto = out.File
	file_base_service_proto_base_proto_goTypes = nil
	file_base_service_proto_base_proto_depIdxs = nil
}
